### ISSUE TITLE
Any releases planned?

### ISSUE THREAD

**Issue by njlr** [beark/ftl#21]
Hello!

Are you planning on marking any commits as releases on GitHub?

**Comment by beark** [comment]
Sorry, for the foreseeable future I've lost interest in this project. It's not being maintained and there's no new planned development.

**Comment by ldionne** [comment]
@beark  You might want to consider rewording the README, which says

> C++ template library for fans of functional programming. The goal of this project is to implement a useful subset of the Haskell Prelude (and a couple of other libraries) in C++. Presently, this subset is small, but rapidly growing. Note, however, that the library and its API are still in heavy flux and the interface of any data type or concept may yet change without notice.

That gives the wrong impression.

**Comment by beark** [comment]
Good point, thanks.
